import{replaceExactlyOnce}from"../../shared/replace.mjs";import{applySleep9922}from"./profile-9922.mjs";import{applySleep10789}from"./profile-10789.mjs";import{applySleep11431}from"./profile-11431.mjs";export const ROOT_ENTRY="webview/assets/app-initial-9b95fa538c62.js",MASCOT_ENTRY="webview/assets/avatar-mascot-button-c97748e2485e.js",OVERLAY_ENTRY="webview/assets/avatar-overlay-native-page-bb89afb2a8f6.js";
const swaps=[
["function Glo(e,t){return`${e.columnIndex/(Klo-1)*100}% ${t==null?`calc(-${e.rowIndex} * var(--codex-pet-frame-height))`:`${e.rowIndex/(t-1)*100}%`}`}","function Glo(e,t){return`${e.columnIndex/(Klo-1)*100}% ${t==null?`calc(-${e.rowIndex} * var(--codex-pet-frame-height))`:t===1?`0%`:`${e.rowIndex/(t-1)*100}%`}`}"],
["ruo=({assetMap:e,className:t,lookFrame:n,respondToHover:r=!1,source:i,state:a=`idle`})=>{","ruo=({assetMap:e,className:t,lookFrame:n,respondToHover:r=!1,sleepPresentation:p=null,source:i,state:a=`idle`})=>{"],
["l=AXe(),u=r&&o?`jumping`:a,d=i.assetRef==null?i.spriteRowCount:r4.rows;","l=AXe(),u=p!=null?`sleep`:r&&o?`jumping`:a,d=p!=null?1:i.assetRef==null?i.spriteRowCount:r4.rows;"],
["if(n!=null){e.style.backgroundPosition=Glo(n,d);return}let t=Ulo(u,l),r=t.frames","if(p==null&&n!=null){e.style.backgroundPosition=Glo(n,d);return}let t=p!=null?{frames:Array.from({length:l?1:p.frameCount},(e,t)=>({columnIndex:t,frameDurationMs:p.frameDurationMs,rowIndex:0})),loopStartIndex:l||!p.loop?null:0}:Ulo(u,l),r=t.frames"],
["},[u,n,l,d]),","},[u,n,l,d,p]),"],["backgroundImage:`url(${i.spritesheetUrl??e[i.assetRef]})`,backgroundSize:","backgroundImage:`url(${p?.assetDataUrl??i.spritesheetUrl??e[i.assetRef]})`,backgroundSize:"]];
function patchMascot(text,caps){const registry=JSON.stringify(caps),lookup="P3i=o.petId??o.assetRef,P3k=typeof P3i===`string`&&P3i.startsWith(`custom:`)?P3i.slice(7):P3i,P3p=typeof P3k===`string`&&/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(P3k)?P3c[P3k]??null:null",effect=`[u,d]=(0,M.useState)(!1),[P3s,P3S]=(0,M.useState)(!1),[P3r,P3R]=(0,M.useState)(0),${lookup},P3e=P3p!=null&&P3p.enabled===!0&&l===\`idle\`&&P3n===!1&&ne==null,P3a=P3s&&P3e;(0,M.useEffect)(()=>{if(!P3e){P3s&&P3S(!1);return}if(P3s)return;let e=window.setTimeout(()=>P3S(!0),P3p.inactivityMs);return()=>window.clearTimeout(e)},[P3e,P3s,P3r,P3p?.inactivityMs]);let f=`;let s=text;s=replaceExactlyOnce(s,"function j(e){let t=(0,fe.c)(20),",`var P3c=${registry};function j(e){let t=(0,fe.c)(21),`,"mascot component entry");for(const[a,b,l]of[["{ariaLabel:n,className:r,lookFrame:ee,notificationBadge:i,","{ariaLabel:n,className:r,hasNotifications:P3n=!1,lookFrame:ee,notificationBadge:i,","props"],["[u,d]=(0,M.useState)(!1),f=",effect,"sleep state"],["f=ne??(u?`jumping`:l)","f=P3a?`sleep`:ne??(u?`jumping`:l)","presentation priority"],["let _=n==null&&!p||void 0,v,y;","let _=n==null&&!p||void 0,v,y,P3d;","handler local"],["(v=()=>{d(!0)},y=()=>{d(!1)},t[2]=v,t[3]=y):(v=t[2],y=t[3]);","(v=()=>{d(!0)},y=()=>{d(!1)},P3d=e=>{e.button===0&&(P3S(!1),P3R(e=>e+1))},t[2]=v,t[3]=y,t[20]=P3d):(v=t[2],y=t[3],P3d=t[20]);","wake handler"],["let b=ee!=null&&f===`jumping`?ee:re?ee:null","let b=P3a?null:ee!=null&&f===`jumping`?ee:re?ee:null","sleep gaze precedence"],["lookFrame:b,source:o,state:f","lookFrame:b,sleepPresentation:P3a?P3p:null,source:o,state:f","sleep render props"],["role:m,onContextMenu:a,onPointerEnter:v","role:m,onContextMenu:a,onPointerDownCapture:P3d,onPointerEnter:v","pointer down"],["\"data-testid\":`avatar-mascot-button`","\"data-testid\":`avatar-mascot-button`,\"data-codex-pet-semantic-state\":l,\"data-codex-pet-sleep-eligible\":P3e,\"data-codex-pet-sleeping\":P3a||void 0","diagnostic attributes"]])s=replaceExactlyOnce(s,a,b,l);return s}
export function applySleep(entries,c,caps,profile="26.908.40834-build-8881"){if(!c.enabled)return{changedEntries:[]};if(profile==="26.924.20706-build-11431")return applySleep11431(entries,c,caps);if(profile==="26.917.62051-build-10789")return applySleep10789(entries,c,caps);if(profile==="26.915.31945-build-9922")return applySleep9922(entries,c,caps);if(profile!=="26.908.40834-build-8881")throw new Error(`Unsupported sleep transform profile: ${profile}`);let root=entries.get(ROOT_ENTRY).toString("utf8");for(const[a,b]of swaps)root=replaceExactlyOnce(root,a,b,"sleep renderer fragment");const mascot=patchMascot(entries.get(MASCOT_ENTRY).toString("utf8"),caps),overlay=replaceExactlyOnce(entries.get(OVERLAY_ENTRY).toString("utf8"),"lookFrame:Dn,notificationBadge:It||Tn?void 0:br","hasNotifications:wt,lookFrame:Dn,notificationBadge:It||Tn?void 0:br","notification signal");entries.set(ROOT_ENTRY,Buffer.from(root));entries.set(MASCOT_ENTRY,Buffer.from(mascot));entries.set(OVERLAY_ENTRY,Buffer.from(overlay));return{changedEntries:[ROOT_ENTRY,MASCOT_ENTRY,OVERLAY_ENTRY],capabilityPetIds:Object.keys(caps)}}
